### ISSUE TITLE
"Include HTML Tags" doesn't generate proper closing tags

### ISSUE THREAD

**Issue by danielcreid** [OneDamnPixel/happy-little-ipsum#17]
![image](https://user-images.githubusercontent.com/3790022/43866155-63548540-9b2a-11e8-8264-4f231e076dc6.png)

**Comment by cmegown** [comment]
😱

**Comment by danielcreid** [comment]
Found this one when trying to QA some things... can't believe we didn't notice this when we first completed this project.

**Comment by danielcreid** [comment]
Fixed with #18
